ilkapp/urls.py
from django.urls import path ,include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import url,include
from django.contrib.auth.models import User
#from django.contrib.auth.views import PasswordChangeView,PasswordChangeDoneView
from django.contrib.auth import views as auth_views
#from django.contrib.auth.views import PasswordChangeDoneView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name="index"),
    path('index1/<kurum>', views.index1, name="index1"),
    path('create/', views.create, name="create"),
    path('delete/<ilkapp_id>', views.delete, name="delete"),
    path('yesFinish/<ilkapp_id>', views.yesFinish, name="yesFinish"),
    path('noFinish/<ilkapp_id>', views.noFinish, name="noFinish"),
    path('update/<ilkapp_id>', views.update, name="update"),
    path('ogrekle/', views.ogrekle, name="ogrekle"),
    path('goster/', views.goster, name="goster"),
    path('ogrFiltre/', views.ogrFiltre, name="ogrFiltre"),
    
    path('user_login/', views.user_login, name="user_login"),
    path('register/<kurum>', views.register, name="register"),
    path('kurumkayit/', views.kurumkayit, name="kurumkayit"),
    path('ogretmenkayit/<kurum>', views.ogretmenkayit, name="ogretmenkayit"),
    path('special/',views.special,name="special"),
   
    path('logout/$', views.user_logout, name="logout"),
    path('ogrenciprofil', views.ogrenciprofil, name="ogrenciprofil"),
    path('accounts/password/',auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/change-password-done/',auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('avatar/', include('avatar.urls')),
    path('ogrenciprofil', views.ogrenciprofil, name="ogrenciprofil"),
    path('sinifekle/<kurum>', views.sinifekle, name="sinifekle"),
    path('deletesinif/<ksinifi_id>', views.deletesinif, name="deletesinif"),
    path('sinifupdate/<ksinifi_id>', views.sinifupdate, name="sinifupdate"),
    path('siniflisteleri/<kurum>/<ksinifi_id>', views.siniflisteleri, name="siniflisteleri"),
    path('ogrencibilgileri/<kurum>/<ogrenci_id>', views.ogrencibilgileri, name="ogrencibilgileri"),
    path('dersekle/<kurum>', views.dersekle, name="dersekle"),
    path('deleteders/<kurum>/<ders_id>', views.deleteders, name="deleteders"),
    path('ogretmenlistesi/<ders_adi>/<kurum>', views.ogretmenlistesi, name="ogretmenlistesi"),
    path('birebirekle/<kurum>', views.birebirekle, name="birebirekle"),
    path('ogrencilistesi/<kurum>', views.ogrencilistesi, name="ogrencilistesi"),
    path('ogrencibbdp/<kurum>/<ogrenci_id>', views.ogrencibbdp, name="ogrencibbdp"),
    path('ogretmenbbdp/<kurum>/<ogrenci_id>', views.ogretmenbbdp, name="ogretmenbbdp"),
    path('deletebb/<kurum>/<bb_id>/<gurup>/', views.deletebb, name="deletebb"),
    path('ogrbirebirekle/<kurum>/<ogrenci_id>/<gurubu>', views.ogrbirebirekle, name="ogrbirebirekle"),
    path('gunekle', views.gunekle, name="gunekle"),
    path('pdfolustur/<adi>/<gurubu>', views.pdfolustur, name="pdfolustur"),
    path('message/<kurum>/<sinif>/',views.message, name="message"),
    path('download/<resim_id>/',views.download, name="download"),
    path('gelenmesaj/<kurum>', views.gelenmesaj, name="gelenmesaj"),
    path('mesajoku/<mesaj_id>', views.mesajoku, name="mesajoku"),
    path('ajaxdeneme', views.ajaxdeneme, name="ajaxdeneme"),
    path('post/ajax/friend', views.postFriend, name = "post_friend"),
    path('get/ajax/validate/nickname', views.checkNickName, name = "validate_nickname"),
    path('post/ajax/ogrbirebireklekaydet/<kurum>/<ogrenci_id>/<gurubu>',views.ogrbirebireklekaydet, name="ogrbirebireklekaydet"),
    path('get/ajax/validate/checkusername', views.checkusername, name = "checkusername"),
    path('duyuru/<kurum>/',views.duyuru, name="duyuru"),
    path('deleteduyuru/<kurum>/<duyuru_id>',views.deleteduyuru, name="deleteduyuru"),
    path('ogrenciara/<kurum>',views.ogrenciara, name="ogrenciara"),
    path('updateduyuru/<kurum>/<duyuru_id>',views.updateduyuru, name="updateduyuru"),
    path('ogrenciduzenle/<kurum>/<ogrenci_id>', views.ogrenciduzenle, name="ogrenciduzenle"),
    path('muhasebe/<kurum>/<ogrenci_id>', views.muhasebe, name="muhasebe"),
    path('erisim/', views.erisim, name="erisim"),
    path('yetkiver/<ogretmen_id>', views.yetkiver, name="yetkiver"),
    path('ogrencisil/<ogrenci_id>', views.ogrencisil, name="ogrencisil"),
    path('sifredegistir/<ogrenci_id>', views.sifredegistir, name="sifredegistir"),
    path('odemem/<kurum>', views.odemem, name="odemem"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('', include('ilkapp.urls')),
    
    
]

ilkapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class ilkapp(models.Model):
    title= models.CharField(max_length=100, blank=True, null=True)
    description=models.TextField(max_length=1000, blank=True, null=True)
    finished=models.BooleanField(default=False)
    date=models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return self.title
#class ogrenci(models.Model):
 #   adi=models.CharField(max_length=100, blank=True, null=True)
  #  telefonu=models.CharField(max_length=100, blank=True, null=True)
   # sinifi=models.CharField(max_length=100, blank=True, null=True)
    #numarasi=models.CharField(max_length=100, blank=True, null=True)
    #def __str__(self):
     #   return self.adi

class ogrenciKayit(models.Model):
    #user = models.OneToOneField(User,on_delete=models.CASCADE)
    username=models.CharField(max_length=50, blank=True, null=True)
    first_name=models.CharField(max_length=100, blank=True, null=True)
    last_name=models.CharField(max_length=100, blank=True, null=True)
    email=models.CharField(max_length=100, blank=True, null=True)
    telefonu=models.CharField(max_length=15, blank=True, null=True)
    sinifi=models.CharField(max_length=10, blank=True, null=True)
    veliadi=models.CharField(max_length=100, blank=True, null=True)
    velitelefonu=models.CharField(max_length=100, blank=True, null=True)
    birebirsaati=models.CharField(max_length=5, blank=True, null=True)
    alani=models.CharField(max_length=100, blank=True, null=True)
    okulu=models.CharField(max_length=100, blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile',blank=True)
    ksinifi=models.CharField(max_length=100, blank=True, null=True)
    ucret=models.PositiveSmallIntegerField(blank=True, null=True)
    taksitsayisi=models.PositiveSmallIntegerField(blank=True, null=True)
    ogrenciadres=models.CharField(max_length=250, blank=True, null=True)
    
    def __str__(self):
         return self.username

class kurums(models.Model):
    
    
    username=models.CharField(max_length=50, blank=True, null=True)
    first_name=models.CharField(max_length=100, blank=True, null=True)
    last_name=models.CharField(max_length=100, blank=True, null=True)
    email=models.CharField(max_length=100, blank=True, null=True)
    telefonu=models.CharField(max_length=15, blank=True, null=True)
    adres=models.CharField(max_length=100, blank=True, null=True)
    ili=models.CharField(max_length=100, blank=True, null=True)
    ilcesi=models.CharField(max_length=100, blank=True, null=True)
    logo=models.ImageField(upload_to='logom', blank=True, null=True)
    vergidairesi=models.CharField(max_length=100, blank=True, null=True)
    verginumarasi=models.CharField(max_length=100, blank=True, null=True)
    #def image_thumb(self):
     #   return '<img src="%s" height="200" width="300"/>' %(self.logo.url)
    
    def __str__(self):
         return self.username

class ogretmenKayit(models.Model):
    #user = models.OneToOneField(User,on_delete=models.CASCADE)
    username=models.CharField(max_length=50, blank=True, null=True)
    first_name=models.CharField(max_length=100, blank=True, null=True)
    last_name=models.CharField(max_length=100, blank=True, null=True)
    email=models.CharField(max_length=100, blank=True, null=True)
    telefonu=models.CharField(max_length=15, blank=True, null=True)
    adres=models.CharField(max_length=10, blank=True, null=True)
    bransi=models.CharField(max_length=100, blank=True, null=True)
    yanbransi=models.CharField(max_length=100, blank=True, null=True)
    iban=models.CharField(max_length=100, blank=True, null=True)
    idareci=models.BooleanField(default=False)
    muhasebe=models.BooleanField(default=False)
    birebirsaati=models.CharField(max_length=5, blank=True, null=True)
    
   
    def __str__(self):
         return self.username

class ksinifi(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    ksinifi=models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
         return self.last_name

class dersler(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    dersadi=models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
         return self.last_name

class birebir(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    bbdersadi=models.CharField(max_length=100, blank=True, null=True)
    bbogrenci=models.CharField(max_length=100, blank=True, null=True)
    bbogrenciid=models.CharField(max_length=100, blank=True, null=True)
    bbogretmen=models.CharField(max_length=100, blank=True, null=True)
    bbogretmenid=models.CharField(max_length=100, blank=True, null=True)
    bbgun=models.PositiveSmallIntegerField(blank=True, null=True)
    bbsaati=models.CharField(max_length=10, blank=True, null=True)
    bbbitissaati=models.CharField(max_length=10, blank=True, null=True)
    bbonay=models.BooleanField(default=False) 
    
      
    #bbgun=models.PositiveSmallIntegerField(max_length=1,blank=True, null=True)
    def __str__(self):
         return self.last_name

class hafta(models.Model):
    gunler=models.CharField(max_length=10, blank=True, null=True)
    def __str__(self):
         return self.gunler

class mesajlar(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    gonderen=models.CharField(max_length=100, blank=True, null=True)
    alici=models.CharField(max_length=100, blank=True, null=True)
    mesaj=models.TextField(max_length=1000, blank=True, null=True)
    baslik=models.CharField(max_length=100, blank=True, null=True)
    resim=models.FileField(upload_to='mesajfile',blank=True)
    tarih=models.DateTimeField(default=datetime.now, blank=True, null=True)
    okundu=models.BooleanField(default=False) 
    def __str__(self):
         return self.gonderen

class Friend(models.Model):
    # NICK NAME should be unique
    nick_name = models.CharField(max_length=100, unique =  True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    likes = models.TextField(max_length=2000, blank=True, null=True)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    lives_in = models.CharField(max_length=150, null = True, blank = True)

    def __str__(self):
        return self.nick_name

class duyurular(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    dgonderen=models.CharField(max_length=100, blank=True, null=True)
    duyuru=models.TextField(max_length=2000, blank=True, null=True)
    dbaslik=models.CharField(max_length=100, blank=True, null=True)
    dtarih=models.DateTimeField(default=datetime.now, blank=True, null=True)
    dogretmen=models.BooleanField(default=True) 
    dogrenci=models.BooleanField(default=True) 
    def __str__(self):
         return self.dbaslik

class dersprogrami(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    dpsinif=models.CharField(max_length=100, blank=True, null=True)
    dpogretmen=models.CharField(max_length=100, blank=True, null=True)
    dpsaat=models.CharField(max_length=10, blank=True, null=True)
    dpders=models.CharField(max_length=100, blank=True, null=True)
    dpgun=models.CharField(max_length=100, blank=True, null=True)
    dersgurubu=models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
         return self.last_name

class derssaatleri(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    dersgurubu=models.CharField(max_length=100, blank=True, null=True)
    derssirasi=models.CharField(max_length=10, blank=True, null=True)
    baslamasaati=models.CharField(max_length=10, blank=True, null=True)
    bitissaati=models.CharField(max_length=10, blank=True, null=True)
    def __str__(self):
         return self.last_name

class dersguruplari(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    dersgurubu=models.CharField(max_length=100, blank=True, null=True)
    derssayisi=models.PositiveSmallIntegerField(blank=True, null=True)
    aciklama=models.TextField(max_length=2000, blank=True, null=True)
    def __str__(self):
         return self.last_name

class odeme(models.Model):
    last_name=models.CharField(max_length=100, blank=True, null=True)
    odogrenci=models.CharField(max_length=100, blank=True, null=True)
    taksit=models.FloatField(blank=True, null=True)
    aciklama=models.CharField(max_length=150, blank=True, null=True)
    odendi=models.BooleanField(default=False)
    odemetarihi=models.DateTimeField(default=datetime.now, blank=True, null=True)
    odemeyialan=models.CharField(max_length=50, blank=True, null=True)
    def __str__(self):
         return self.odogrenci

ilkapp/forms.py
from django import forms
from . models import *
from django.contrib.auth.models import User
import datetime

class listForm(forms.ModelForm):
    class Meta:
        model = ilkapp
        fields=("title","description","finished","date")
    

#class ogrenciform(forms.ModelForm):
 #   class Meta:
  #      model=ogrenci
   #     fields=("adi","telefonu","sinifi","numarasi")



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email','first_name','last_name','groups')
class ogrenciKayitForm(forms.ModelForm):
     class Meta():
         model = ogrenciKayit
         fields = ("__all__")

class kurumsForm(forms.ModelForm):
     class Meta():
         model = kurums
         fields = ("__all__")

class ogretmenForm(forms.ModelForm):
    class Meta():
         model = ogretmenKayit
         fields = ("__all__")

class ksinifiForm(forms.ModelForm):
    class Meta():
         model = ksinifi
         fields = ("last_name","ksinifi")

class dersekleForm(forms.ModelForm):
    class Meta():
         model = dersler
         fields = ("last_name","dersadi")
class birebirForm(forms.ModelForm):
    class Meta():
         model = birebir
         fields = ("__all__")
         
class haftaForm(forms.ModelForm):
    class Meta():
         model = hafta
         fields = ('gunler',)

class mesajlarForm(forms.ModelForm):
    class Meta():
        model = mesajlar
        fields=("__all__")

class FriendForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(FriendForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Friend
        fields = ("__all__")

class duyurularForm(forms.ModelForm):
    class Meta():
         model = duyurular
         fields = ("__all__")

class dersprogramiForm(forms.ModelForm):
    class Meta():
         model = dersprogrami
         fields = ("__all__")

class derssaatleriForm(forms.ModelForm):
    class Meta():
         model = derssaatleri
         fields = ("__all__")

class dersguruplariForm(forms.ModelForm):
    class Meta():
         model = dersguruplari
         fields = ("__all__")

class odemeForm(forms.ModelForm):
    class Meta():
         model = odeme
         fields = ("__all__")

templates/ilkapp/about.html
{% extends "ilkapp/base.html" %}
{% block title %}
About
{% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><center>TODO List</center></h1>
      <p class="lead"><center>yapılacaklar listesi</center></p>
      <p class="lead"><center>yapılacaklar listesi hazırlayın</center></p>
      <p class="lead"><center>yapılacaklar listesi düzenleyin</center></p>
      <p class="lead"><center>yapılacaklar listesi yayınlayın</center></p>
      <p><center><a type="button" class="btn btn-outline-success" href="{% url 'create' %}">Listeye Ekle</a></center></p>
    </div>
  </div>
{% endblock content %}

templates/ilkapp/create.html
{% extends "ilkapp/base.html" %}
{% block title %}
Create
{% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><center>TODO List</center></h1>
      <p class="lead"><center>yapılacaklar listesi</center></p>
      <div>
        <form method="POST">
          {% csrf_token %} 
            <div class="form-group row">
              <label for="inputEmail3" class="col-sm-2 col-form-label" >Title</label>
              <div class="col-sm-10">
                <input type="text" class="form-control"  placeholder="ToDo" name="title">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-2 col-form-label">Açıklama</label>
              <div class="col-sm-10">
                <input type="text" class="form-control"  placeholder="Açıklama" name="description">
              </div>
            </div>
            <fieldset class="form-group">
              
              </div>
            </fieldset>
            <div class="form-group row">
              <div class="col-sm-2">Bitti</div>
              <div class="col-sm-10">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="gridCheck1" name="finished">
                  <label class="form-check-label" >
                    Evet
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Kaydet</button>
              </div>
            </div>
          </form>
      </div>
    </div>   
{% endblock content %}

templates/ilkapp/goster.html
{% extends "ilkapp/base.html" %}
{% block title %}
göster
{% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><center>TODO List</center></h1>
      <p class="lead"><center>yapılacaklar listesi</center></p>
      <p><center><a type="button" class="btn btn-outline-success" href="{% url 'create' %}">Listeye Ekle</a></center></p>
    </div>
  </div>
  <div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">ToDo Adı</th>
      <th scope="col">Bitti</th>
      <th scope="col">Tarih</th>
      <th scope="col">Sil</th>
      <th scope="col">Güncelle</th>
    </tr>
  </thead>
  <tbody>
   {% for todo in liste %}
    <tr>
      <td scope="col">{{todo.adi}}</td>
      <td scope="col">{{todo.sinifi}}</td>
      <td scope="col">{{todo.telefonu}}</td>
      <td scope="col">{{todo.numarasi}}</td>
   {% endfor %}
  </tbody>
</table>
{% if liste.has_previous %}
    <a href="?sayfa={{ liste.previous_page_number }}">Önceki</a>
{% endif %}
 
{{ liste.number }}
 
{% if liste.has_next %}
    <a href="?sayfa={{liste.next_page_number }}">Sonraki</a> 
{% endif %}
 <form method="GET" action="{% url 'ogrFiltre' %}">
      {% csrf_token %}
<div class="form-row">
    <div class="form-group col-sm-10">
      <label >adı</label>
      <input type="text" class="form-control" name="ogrenci_adi" placeholder="adı">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        {% for todo in liste %}
        <option>{{todo.adi}}</option>
         {% endfor %}
      </select>
    </div>
    <div class="col-sm-10">
                <button  type="submit" class="btn btn-success">filtrele</button>
    </div>
    
</form>
    </div>   
    </div>
</div>

 
 
  
  
{% endblock content %}

templates/ilkapp/ogrenciduzenle.html
{% extends "ilkapp/base.html" %}
{% load auth_extras %}
{% block title %}
Öğrenci Kayıt
{% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      {% if registered %}
        <h1>Kayıt İşlemi Başarılı</h1>
         
            {% if user.is_authenticated and request.user|has_group:"idare" %}
              <a  class="btn btn-light" href="{% url 'register' user.last_name %}">Yeni Kayıt</a>
            {% elif user.is_authenticated and  request.user|has_group:"kurum" %}
            <a  class="btn btn-light" href="{% url 'register' user.username %}">Yeni Kayıt</a>
            {%endif%}
      {% else %}
        <h1>Öğrenci Kayıt Formu</h1>
        <h3>Tüm Alanları doldurun.</h3>

        </div>
        </div>
        <div class="container">
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
   {% if user.is_authenticated and request.user|has_group:"kurum" %}
      <div class="form-group col-sm-10">
       <label >Kurum Kodu</label>
       <input type="text" class="form-control-plaintext" name="last_name"  value="{{user.username}}" readonly>
      </div>   
  {% elif user.is_authenticated and request.user|has_group:"idare" %} 
    
  <div class="form-group col-sm-10">
      <label >Kurum Kodu</label>
      <input type="text" readonly class="form-control-plaintext" name="last_name"  value="{{user.last_name}}" >
    </div>  
       
      {%endif%}
    <div class="form-group col-sm-10">
      <label >E-posta Adresi</label>
      <input type="email" readonly class="form-control-plaintext" value="{{todo.username}}" id="id_nick_name" name="username"  placeholder="deneme@deneme.com"  required>
    </div>

    

    <div class="form-group col-sm-10">
      <label >E-mail</label>
      <input type="email" readonly class="form-control-plaintext" value="{{todo.email}}" class="form-control is-valid" name="email" placeholder="eposta" required>
    </div>

    <div class="form-group col-sm-10">
      <label >Adı</label>
      <input type="text" readonly class="form-control-plaintext" value="{{todo.first_name}}" name="first_name" placeholder="Adı" required>
    </div>

    
    <div class="form-group col-sm-10">
      <label >Telefon Numarası</label>
      <input type="text" class="form-control is-valid" value="{{todo.telefonu}}"name="telefonu" placeholder="tel" required>
    </div>
    <div class="form-group col-sm-10">
      <label >Okulu</label>
      <input type="text" class="form-control is-valid" value="{{todo.okulu}}" name="okulu" placeholder="Devam ettiği veya mezun olduğu okul adı" required>
    </div>
   
    <div class="form-group col-sm-10">
      <label >Sınıf Seviyesi</label>
      <select name="sinifi" class="custom-select mr-sm-2 is-valid" required>
  <option>{{todo.sinifi}}</option>
  <option>1</option>
  <option>2</option>
  <option>3</option>
  <option>4</option>
  <option>5</option>
  <option>6</option>
  <option>7</option>
  <option>8</option>
  <option>9</option>
  <option>10</option>
  <option>11</option>
  <option>12</option>
  <option>Mezun</option>
</select>
    </div>
   
    <div class="form-group col-sm-10">
      <label >Alanı</label>
      <select name="alani" class="custom-select mr-sm-2 is-valid" required>
  <option>{{todo.alani}}</option>
  <option>Sayısal</option>
  <option>Sözel</option>
  <option>Eşit Ağırlık</option>
</select>
    </div>

      <div class="form-group col-sm-10" >
      <label >Veli Adı</label>
      <input type="text" class="form-control is-valid" value="{{todo.veliadi}}" required name="veliadi" placeholder="Veli Adı" >
    </div>

    <div class="form-group col-sm-10">
      <label >Veli Telefonu</label>
      <input type="text" class="form-control is-valid" value="{{todo.velitelefonu}}" name="velitelefonu" placeholder="Veli Telefonu"  required>
    </div>

    <div class="form-group col-sm-10" >
      <label >Birebir Ders Saati</label>
      <input type="text" class="form-control is-valid"  value="{{todo.birebirsaati}}" name="birebirsaati" placeholder="Alacağı Birebir Saat" required>
    </div>
  <div class="form-group col-sm-10">
      <label >Sınıfı</label>
      <select name="ksinifi" class="custom-select mr-sm-2 is-valid" required>
      
  <option>{{todo.ksinifi}}</option>
  {%for sinif in siniflar %}
  <option>{{sinif.ksinifi}}</option>
  {%endfor%}

</select>
    </div>
    <div class="form-group col-sm-10">
      <label >Resim</label>
      <input type="file" class="form-control" name="profile_pic" accept="image/*">
    </div>
    
      <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
  Öğrenciyi Kaydet
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Kaydet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Öğrenci kaydı tamamlanacak...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
        <button type="submit"  class="btn btn-primary">Kaydet</button>
      </div>
    </div>
  
</div>
    
        </form>
        
      {% endif %}
  
  
</form>

</div>
{% block javascript %}

{% endblock javascript %}
{% endblock content %}